/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tdei.gateway.controller.common.contract;

import com.tdei.gateway.model.dto.common.Agency;
import com.tdei.gateway.model.dto.common.Station;
import com.tdei.gateway.model.dto.common.VersionList;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Validated
public interface ICommon {
    @Operation(summary = "List Agencies", description = "Returns a list of all `agency` entities. See endpoint description for detail.", security = {
            @SecurityRequirement(name = "ApiKey")}, tags = {})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successful response - returns an array of `Agency` entities.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Agency.class)))),

            @ApiResponse(responseCode = "401", description = "This request is unauthorized. appID is invalid. Please obtain a valid application ID (appID).", content = @Content),

            @ApiResponse(responseCode = "500", description = "An server error occurred.", content = @Content)})
    @RequestMapping(value = "agencies", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<List<Agency>> listAgencies();


    @Operation(summary = "List available API versions", description = "Lists the versions of the TDEI  API which are available.", security = {
            @SecurityRequirement(name = "ApiKey")}, tags = {})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Returns a list of versions", content = @Content(mediaType = "application/json", schema = @Schema(implementation = VersionList.class))),

            @ApiResponse(responseCode = "401", description = "This request is unauthorized. appID is invalid. Please obtain a valid application ID (appID).", content = @Content),

            @ApiResponse(responseCode = "500", description = "An server error occurred.", content = @Content)})
    @RequestMapping(value = "/api", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<VersionList> listApiVersions();


    @Operation(summary = "List Stations", description = "Returns a list of all `Station` entities. See endpoint description for detail.", security = {
            @SecurityRequirement(name = "ApiKey")}, tags = {})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Returns an array of `Station` entities. ", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Station.class)))),

            @ApiResponse(responseCode = "401", description = "This request is unauthorized. appID is invalid. Please obtain a valid application ID (appID)."),

            @ApiResponse(responseCode = "500", description = "An server error occurred.")})
    @RequestMapping(value = "stations", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<List<Station>> listStations();
}

