server:
  port: '8080'
spring:
  config:
    import: optional:developer-local-properties.yaml
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
application:
  app-name: tdei-gateway
  auth-server-url: "${APPLICATION_AUTH_SERVER_URL}"

gtfs-flex:
  upload-url: "${GTFS_FLEX_UPLOAD_URL}"
  data-url: "${GTFS_FLEX_DATA_URL}"
gtfs-pathways:
  upload-url: "${GTFS_PATHWAYS_UPLOAD_URL}"
  data-url: "${GTFS_PATHWAYS_DATA_URL}"
osw:
  upload-url: "${OSW_UPLOAD_URL}"
  data-url: "${OSW_DATA_URL}"
management-svc:
  station-url: "${MANAGEMENT_SVC_STATION_URL}"
  service-url: "${MANAGEMENT_SVC_SERVICE_URL}"
  org-url: "${MANAGEMENT_SVC_ORG_URL}"
  logger-url: "${MANAGEMENT_SVC_LOGGER_URL}"
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: This is an API for publishing data to the Transportation Data Equity Initiative (TDEI) data system. This API is intended for applications producing data for and consuming data from the TDEI system. This API supports publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks data to the TDEI.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI Gateway API
  version: v0.1
