spring:
  application:
    name: tdei-gateway
server:
  port: '8080'
auth-server-url: http://localhost:8082
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: This is an API for applications consuming data from and publishing
    data to the Transportation Data Equity Initiative (TDEI) data system. This API
    supports consuming and publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks
    data from and to the TDEI.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI API
  version: v0.1