server:
  port: '8080'

application:
  app-name: tdei-gateway
  auth-server-url: https://tdei-authz.azurewebsites.net
  #http://localhost:8082

gtfs-flex:
  upload-url: http://localhost:8083/api/gtfsflex/v1/uploadFile
gtfs-pathways:
  upload-url: http://localhost:8083/api/gtfspathways/v1/uploadFile
osw:
  upload-url: http://localhost:8083/api/osw/v1/uploadFile

spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: This is an API for applications consuming data from and publishing
    data to the Transportation Data Equity Initiative (TDEI) data system. This API
    supports consuming and publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks
    data from and to the TDEI.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI Gateway API
  version: v0.1