server:
  port: '8080'
spring:
  config:
    import: optional:developer-local-properties.yaml
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

auth-server-url: "${AUTH_SERVER_URL}"
management-base-url: "${MANAGEMENT_BASE_URL}"
file-upload-base-url: "${FILE_UPLOAD_BASE_URL}}"
gtfs-flex-data-url: "${GTFS_FLEX_DATA_URL}"
gtfs-pathways-data-url: "${GTFS_PATHWAYS_DATA_URL}"
osw-data-url: "${OSW_DATA_URL}"
logger-url: "${LOGGER_URL}"

application:
  app-name: tdei-gateway

spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: This is an API for publishing data to the Transportation Data Equity Initiative (TDEI) data system. This API is intended for applications producing data for and consuming data from the TDEI system. This API supports publishing of GTFS-Pathways, GTFS-Flex v2 and OpenSidewalks data to the TDEI.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI Gateway API
  version: v0.1
