package com.tdei.gateway.model.dto.common;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import org.springframework.validation.annotation.Validated;

import javax.validation.constraints.NotNull;

/**
 * metadata generated by the tdei system. provided when a file is downloaded.
 */
@Schema(description = "metadata generated by the tdei system. provided when a file is downloaded.")
@Validated
@Data
public class TdeiSystemMetadata {
    @JsonProperty("schema_version")
    @Schema(required = true, description = "The version of the data schema associated with this file.")
    @NotNull
    private String schemaVersion = null;

    @JsonProperty("tdei_record_id")
    @Schema(required = true, description = "tdei-assigned data record id")
    @NotNull
    private Integer tdeiRecordId = null;

    @JsonProperty("confidence_level")
    @Schema(required = true, description = "TDEI-assigned confidence level")
    @NotNull
    private Integer confidenceLevel = null;
}
